package nz.org.nesi.envtester.view.swing;

import nz.org.nesi.envtester.TestController;

import javax.swing.*;
import java.awt.*;

public class EnvTestStartDialog extends JDialog {
    private JPanel contentPane;
    private EnvTestStarterPanel envTestStarterPanel1;
    private final TestController tc;

    public EnvTestStartDialog(Frame owner, TestController tc) {
        super(owner);
        if ( tc == null ) {
            this.tc = new TestController();
        } else {
            this.tc = tc;
        }
        setDefaultCloseOperation(HIDE_ON_CLOSE);
        $$$setupUI$$$();
        setContentPane(contentPane);
        setPreferredSize(new Dimension(450, 600));
    }


    public static void main(String[] args) {
        EnvTestStartDialog dialog = new EnvTestStartDialog(null, null);
        dialog.pack();
        dialog.setVisible(true);
    }

    public void createUIComponents() {
        envTestStarterPanel1 = new EnvTestStarterPanel(tc);
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        contentPane = new JPanel();
        contentPane.setLayout(new BorderLayout(0, 0));
        contentPane.add(envTestStarterPanel1, BorderLayout.CENTER);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }
}
